# Generated by Django 4.2.3 on 2023-07-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('elevator_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('maintenance', 'Maintenance')], default='stopped', max_length=12)),
                ('current_floor', models.IntegerField(default=1)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stopped', 'Stopped')], default='stopped', max_length=10)),
                ('elevator_id', models.AutoField(primary_key=True, serialize=False)),
                ('requests', models.ManyToManyField(related_name='elevators', to='elevator_system.request')),
            ],
        ),
    ]
