# Generated by Django 4.2.3 on 2023-07-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='elevator_id',
        ),
    ]
