# Generated by Django 4.2.3 on 2023-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0002_remove_request_elevator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='requests',
            field=models.ManyToManyField(to='elevator_system.request'),
        ),
    ]
